use AdventureWorks
use estoquepython

SELECT * FROM produtos
SELECT * FROM Product
CREATE DATABASE EstoquePython

CREATE TABLE PRODUTOS(
	CODPROD INT NOT NULL PRIMARY KEY,
	DESCPROD VARCHAR(100) NOT NULL,
	QUANTPROD FLOAT(50),
	STATUSPROD BIT NOT NULL
);

INSERT INTO PRODUTOS VALUES (2,'TAMPA',10,1)




SELECt PRODUCTID,NAME,PRODUCTNUMBER,Makeflag from Product
