use AdventureWorks
use estoque
show databases

SELECT * FROM produtos
CREATE DATABASE EstoquePython

CREATE TABLE PRODUTOS(
	CODPROD INT NOT NULL PRIMARY KEY,
	DESCPROD VARCHAR(100) NOT NULL,
	QUANTPROD FLOAT(50),
	STATUSPROD BIT NOT NULL
);

INSERT INTO PRODUTOS VALUES (3,'TAMPA',10,1)




SELECt PRODUCTID,NAME,PRODUCTNUMBER,Makeflag from Product
